// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pawsome.Infrastructure;

#nullable disable

namespace Pawsome.Infrastructure.Migrations
{
    [DbContext(typeof(PawsomeDbContext))]
    [Migration("20260811182714_FixSanPhamVariantNamesEnglish")]
    partial class FixSanPhamVariantNamesEnglish
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pawsome.Domain.Entities.BlogQuanTri.BlogPost", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("anh_dai_dien");

                    b.Property<string>("ChuDe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("chu_de");

                    b.Property<DateTime>("NgayDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_dang")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<int>("TacGiaId")
                        .HasColumnType("int")
                        .HasColumnName("tac_gia_id");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tieu_de");

                    b.HasKey("PostId");

                    b.HasIndex("TacGiaId")
                        .HasDatabaseName("IX_blog_posts_author");

                    b.ToTable("blog_posts", (string)null);

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            ChuDe = "Chó",
                            NgayDang = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDung = "Chó con mới tách mẹ cần thời gian thích nghi với môi trường mới. Hãy chuẩn bị chỗ ngủ ấm áp, lên lịch tiêm phòng đầy đủ, cho ăn đúng cữ với thức ăn dành riêng cho chó con, và tránh cho ra ngoài tiếp xúc với chó lạ trước khi hoàn thành các mũi tiêm cơ bản.",
                            TacGiaId = 1,
                            TieuDe = "5 lưu ý khi chăm sóc chó con mới về nhà"
                        },
                        new
                        {
                            PostId = 2,
                            ChuDe = "Mèo",
                            NgayDang = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDung = "Mèo trưởng thành cần khẩu phần giàu đạm động vật, hạn chế tinh bột. Nên chia 2-3 bữa/ngày, luôn có nước sạch, và tham khảo ý kiến bác sĩ thú y trước khi đổi loại thức ăn đột ngột để tránh rối loạn tiêu hóa.",
                            TacGiaId = 1,
                            TieuDe = "Chế độ dinh dưỡng cho mèo trưởng thành"
                        },
                        new
                        {
                            PostId = 3,
                            ChuDe = "Sức khỏe",
                            NgayDang = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDung = "Thời tiết giao mùa là lúc thú cưng dễ mắc các bệnh về đường hô hấp và tiêu hóa. Chủ nuôi nên giữ ấm, vệ sinh nơi ở sạch sẽ, tiêm phòng định kỳ và quan sát các dấu hiệu bất thường như bỏ ăn, nôn mửa để đưa đi khám kịp thời.",
                            TacGiaId = 1,
                            TieuDe = "Cách phòng bệnh thường gặp ở thú cưng theo mùa"
                        });
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.BlogQuanTri.Wishlist", b =>
                {
                    b.Property<int>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("wishlist_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishlistId"));

                    b.Property<DateTime>("NgayThem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_them")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("WishlistId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_wishlists_product");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_wishlists_user");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UQ_wishlists_user_product");

                    b.ToTable("wishlists", (string)null);
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.Common.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("ChiTiet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chi_tiet");

                    b.Property<string>("DiaChiIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("dia_chi_ip");

                    b.Property<string>("DoiTuong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("doi_tuong");

                    b.Property<int?>("DoiTuongId")
                        .HasColumnType("int")
                        .HasColumnName("doi_tuong_id");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hanh_dong");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("LogId");

                    b.HasIndex("NgayTao")
                        .HasDatabaseName("IX_audit_logs_ngaytao");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_audit_logs_user");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.DonHang.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    b.Property<int?>("CouponId")
                        .HasColumnType("int")
                        .HasColumnName("coupon_id");

                    b.Property<string>("DonViVanChuyen")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("don_vi_van_chuyen");

                    b.Property<decimal>("GiamGia")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("giam_gia");

                    b.Property<string>("MaVanDon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_van_don");

                    b.Property<DateTime>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_dat")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("PhiVanChuyen")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("phi_van_chuyen");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("thanh_tien");

                    b.Property<decimal>("TienHang")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("tien_hang");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("trang_thai");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("OrderId");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("IX_orders_address");

                    b.HasIndex("CouponId")
                        .HasDatabaseName("IX_orders_coupon");

                    b.HasIndex("NgayDat")
                        .HasDatabaseName("IX_orders_ngaydat");

                    b.HasIndex("TrangThai")
                        .HasDatabaseName("IX_orders_trangthai");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_orders_user");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_orders_giamgia", "giam_gia >= 0");

                            t.HasCheckConstraint("CK_orders_phivanchuyen", "phi_van_chuyen >= 0");

                            t.HasCheckConstraint("CK_orders_thanhtien", "thanh_tien >= 0");

                            t.HasCheckConstraint("CK_orders_tienhang", "tien_hang >= 0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.DonHang.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<decimal>("DonGia")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("don_gia");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.Property<int>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("variant_id");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_order_items_order");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("IX_order_items_variant");

                    b.ToTable("order_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_order_items_dongia", "don_gia >= 0");

                            t.HasCheckConstraint("CK_order_items_soluong", "so_luong > 0");
                        });
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.DonHang.PawPointsTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("loai");

                    b.Property<DateTime>("NgayGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_giao_dich")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("SoDiem")
                        .HasColumnType("int")
                        .HasColumnName("so_diem");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("TransactionId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_pawpoints_order");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_pawpoints_user");

                    b.ToTable("pawpoints_transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_pawpoints_loai", "loai IN (N'earn', N'redeem', N'bonus')");

                            t.HasCheckConstraint("CK_pawpoints_sodiem", "so_diem <> 0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.DonHang.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ma_giao_dich");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_thanh_toan");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phuong_thuc");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("so_tien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trang_thai");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_payments_order");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_payments_sotien", "so_tien > 0");
                        });
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.GioHang.AutoOrder", b =>
                {
                    b.Property<int>("AutoOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("auto_order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutoOrderId"));

                    b.Property<DateOnly>("NgayKeTiep")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ke_tiep");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.Property<string>("TanSuat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tan_suat");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("trang_thai");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("variant_id");

                    b.HasKey("AutoOrderId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_auto_orders_user");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("IX_auto_orders_variant");

                    b.ToTable("auto_orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_auto_orders_soluong", "so_luong > 0");

                            t.HasCheckConstraint("CK_auto_orders_trangthai", "trang_thai IN (N'active', N'paused', N'cancelled')");
                        });
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.GioHang.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cart_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("CartId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_carts_user");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.GioHang.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cart_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int")
                        .HasColumnName("cart_id");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("so_luong");

                    b.Property<int>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("variant_id");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId")
                        .HasDatabaseName("IX_cart_items_cart");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("IX_cart_items_variant");

                    b.HasIndex("CartId", "VariantId")
                        .IsUnique()
                        .HasDatabaseName("UQ_cart_items_cart_variant");

                    b.ToTable("cart_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_cart_items_soluong", "so_luong > 0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.GioHang.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("coupon_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<decimal>("GiaTri")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("gia_tri");

                    b.Property<string>("LoaiGiam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("loai_giam");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_code");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.HasKey("CouponId");

                    b.HasIndex("MaCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_coupons_code");

                    b.ToTable("coupons", null, t =>
                        {
                            t.HasCheckConstraint("CK_coupons_gia_tri", "gia_tri > 0");

                            t.HasCheckConstraint("CK_coupons_loai_giam", "loai_giam IN (N'percent', N'fixed')");

                            t.HasCheckConstraint("CK_coupons_ngay", "ngay_bat_dau IS NULL OR ngay_ket_thuc IS NULL OR ngay_ket_thuc >= ngay_bat_dau");

                            t.HasCheckConstraint("CK_coupons_so_luong", "so_luong IS NULL OR so_luong >= 0");
                        });
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.SanPham.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("brand_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("logo_url");

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_thuong_hieu");

                    b.HasKey("BrandId");

                    b.HasIndex("TenThuongHieu")
                        .IsUnique()
                        .HasDatabaseName("UQ_brands_ten");

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.SanPham.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int?>("DanhMucChaId")
                        .HasColumnType("int")
                        .HasColumnName("danh_muc_cha_id");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_danh_muc");

                    b.HasKey("CategoryId");

                    b.HasIndex("DanhMucChaId")
                        .HasDatabaseName("IX_categories_parent");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.SanPham.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("brand_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<bool>("DangKinhDoanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("dang_kinh_doanh");

                    b.Property<decimal>("DiemDanhGiaTb")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)")
                        .HasDefaultValue(0m)
                        .HasColumnName("diem_danh_gia_tb");

                    b.Property<decimal?>("GiaTu")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("gia_tu");

                    b.Property<string>("LieuLuong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lieu_luong");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ten");

                    b.HasKey("ProductId");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("IX_products_brand");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_products_category");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("CK_products_diem_danh_gia", "diem_danh_gia_tb BETWEEN 0 AND 5");

                            t.HasCheckConstraint("CK_products_gia_tu", "gia_tu IS NULL OR gia_tu >= 0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.SanPham.ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("image_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<bool>("LaAnhChinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("la_anh_chinh");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("url");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_images_product");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.SanPham.ProductVariant", b =>
                {
                    b.Property<int>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("variant_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VariantId"));

                    b.Property<bool>("DangKinhDoanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("dang_kinh_doanh");

                    b.Property<decimal>("Gia")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("gia");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sku");

                    b.Property<int>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("so_luong_ton");

                    b.Property<string>("TenBienThe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_bien_the");

                    b.HasKey("VariantId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_variants_product");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("UQ_product_variants_sku")
                        .HasFilter("[sku] IS NOT NULL");

                    b.ToTable("product_variants", null, t =>
                        {
                            t.HasCheckConstraint("CK_variants_gia", "gia > 0");

                            t.HasCheckConstraint("CK_variants_soluongton", "so_luong_ton >= 0");
                        });
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.SanPham.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("BinhLuan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("binh_luan");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<byte>("SoSao")
                        .HasColumnType("tinyint")
                        .HasColumnName("so_sao");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("cho_duyet")
                        .HasColumnName("trang_thai");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ReviewId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_reviews_product");

                    b.HasIndex("TrangThai")
                        .HasDatabaseName("IX_reviews_trangthai");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_reviews_user");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_reviews_sosao", "so_sao BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_reviews_trangthai", "trang_thai IN (N'cho_duyet', N'da_duyet', N'tu_choi')");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.TaiKhoan.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("DiaChiChiTiet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dia_chi_chi_tiet");

                    b.Property<bool>("LaMacDinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("la_mac_dinh");

                    b.Property<string>("NguoiNhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nguoi_nhan");

                    b.Property<string>("PhuongXa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("phuong_xa");

                    b.Property<string>("QuanHuyen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("quan_huyen");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TinhThanh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tinh_thanh");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_addresses_user");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.TaiKhoan.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_vai_tro");

                    b.HasKey("RoleId");

                    b.HasIndex("TenVaiTro")
                        .IsUnique()
                        .HasDatabaseName("UQ_roles_ten");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            MoTa = "Khách hàng - người mua sản phẩm",
                            TenVaiTro = "Customer"
                        },
                        new
                        {
                            RoleId = 2,
                            MoTa = "Quản trị viên - quản lý toàn hệ thống",
                            TenVaiTro = "Admin"
                        },
                        new
                        {
                            RoleId = 3,
                            MoTa = "Người kiểm duyệt - duyệt đánh giá, nội dung",
                            TenVaiTro = "Moderator"
                        },
                        new
                        {
                            RoleId = 4,
                            MoTa = "Nhân viên hỗ trợ - chăm sóc khách hàng",
                            TenVaiTro = "Support"
                        });
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.TaiKhoan.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("DiemPawpoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("diem_pawpoints");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<DateTime>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("trang_thai");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_users_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_users_role");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_users_diem_pawpoints", "diem_pawpoints >= 0");

                            t.HasCheckConstraint("CK_users_trangthai", "trang_thai IN (N'active', N'locked')");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DiemPawpoints = 0,
                            Email = "admin@pawsome.vn",
                            HoTen = "Quản trị viên",
                            NgayCapNhat = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "$2a$11$VOB3KJqGRdIg7DYWqdKumuDJRPl4ED3pUwy36ArnXBg39m9Gz8wB.",
                            RoleId = 2,
                            TrangThai = "active"
                        });
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.BlogQuanTri.BlogPost", b =>
                {
                    b.HasOne("Pawsome.Domain.Entities.TaiKhoan.User", "TacGia")
                        .WithMany("BlogPosts")
                        .HasForeignKey("TacGiaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_blog_posts_users");

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.BlogQuanTri.Wishlist", b =>
                {
                    b.HasOne("Pawsome.Domain.Entities.SanPham.Product", "Product")
                        .WithMany("Wishlists")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_wishlists_products");

                    b.HasOne("Pawsome.Domain.Entities.TaiKhoan.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_wishlists_users");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.Common.AuditLog", b =>
                {
                    b.HasOne("Pawsome.Domain.Entities.TaiKhoan.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_audit_logs_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.DonHang.Order", b =>
                {
                    b.HasOne("Pawsome.Domain.Entities.TaiKhoan.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_orders_addresses");

                    b.HasOne("Pawsome.Domain.Entities.GioHang.Coupon", "Coupon")
                        .WithMany("Orders")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_orders_coupons");

                    b.HasOne("Pawsome.Domain.Entities.TaiKhoan.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_orders_users");

                    b.Navigation("Address");

                    b.Navigation("Coupon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.DonHang.OrderItem", b =>
                {
                    b.HasOne("Pawsome.Domain.Entities.DonHang.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_order_items_orders");

                    b.HasOne("Pawsome.Domain.Entities.SanPham.ProductVariant", "Variant")
                        .WithMany("OrderItems")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_order_items_variants");

                    b.Navigation("Order");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.DonHang.PawPointsTransaction", b =>
                {
                    b.HasOne("Pawsome.Domain.Entities.DonHang.Order", "Order")
                        .WithMany("PawPointsTransactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_pawpoints_orders");

                    b.HasOne("Pawsome.Domain.Entities.TaiKhoan.User", "User")
                        .WithMany("PawPointsTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_pawpoints_users");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.DonHang.Payment", b =>
                {
                    b.HasOne("Pawsome.Domain.Entities.DonHang.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_payments_orders");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.GioHang.AutoOrder", b =>
                {
                    b.HasOne("Pawsome.Domain.Entities.TaiKhoan.User", "User")
                        .WithMany("AutoOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_auto_orders_users");

                    b.HasOne("Pawsome.Domain.Entities.SanPham.ProductVariant", "Variant")
                        .WithMany("AutoOrders")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_auto_orders_variants");

                    b.Navigation("User");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.GioHang.Cart", b =>
                {
                    b.HasOne("Pawsome.Domain.Entities.TaiKhoan.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("Pawsome.Domain.Entities.GioHang.Cart", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_carts_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.GioHang.CartItem", b =>
                {
                    b.HasOne("Pawsome.Domain.Entities.GioHang.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_cart_items_carts");

                    b.HasOne("Pawsome.Domain.Entities.SanPham.ProductVariant", "Variant")
                        .WithMany("CartItems")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_cart_items_variants");

                    b.Navigation("Cart");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.SanPham.Category", b =>
                {
                    b.HasOne("Pawsome.Domain.Entities.SanPham.Category", "DanhMucCha")
                        .WithMany("DanhMucCon")
                        .HasForeignKey("DanhMucChaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_categories_parent");

                    b.Navigation("DanhMucCha");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.SanPham.Product", b =>
                {
                    b.HasOne("Pawsome.Domain.Entities.SanPham.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_products_brands");

                    b.HasOne("Pawsome.Domain.Entities.SanPham.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_products_categories");

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.SanPham.ProductImage", b =>
                {
                    b.HasOne("Pawsome.Domain.Entities.SanPham.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_images_products");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.SanPham.ProductVariant", b =>
                {
                    b.HasOne("Pawsome.Domain.Entities.SanPham.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_variants_products");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.SanPham.Review", b =>
                {
                    b.HasOne("Pawsome.Domain.Entities.SanPham.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_reviews_products");

                    b.HasOne("Pawsome.Domain.Entities.TaiKhoan.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_reviews_users");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.TaiKhoan.Address", b =>
                {
                    b.HasOne("Pawsome.Domain.Entities.TaiKhoan.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_addresses_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.TaiKhoan.User", b =>
                {
                    b.HasOne("Pawsome.Domain.Entities.TaiKhoan.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_users_roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.DonHang.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("PawPointsTransactions");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.GioHang.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.GioHang.Coupon", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.SanPham.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.SanPham.Category", b =>
                {
                    b.Navigation("DanhMucCon");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.SanPham.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");

                    b.Navigation("Variants");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.SanPham.ProductVariant", b =>
                {
                    b.Navigation("AutoOrders");

                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.TaiKhoan.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.TaiKhoan.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Pawsome.Domain.Entities.TaiKhoan.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("AuditLogs");

                    b.Navigation("AutoOrders");

                    b.Navigation("BlogPosts");

                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("PawPointsTransactions");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
